---

- hosts: hello
  tasks:
    - name: hello world {{ ansible }} this is very cool :)
      when: hello == "good"

    - name: template demo
      ansible.builtin.template: |
        {% if hello %}
          {{ hello }}
          {{ world }}
          {{ cool }}
        {% endif %}



    - name: hello
      when: hello

    - name: hello
      action: hello
      throttle: 3

    - name: demo
      block:
        - name: hello world
          task: hello
