- hosts: server
  tasks:
    - name: this {{ ansible_bios_version }} cool
      action: ansible.builtin.apt

    - name: debug
      ansible.builtin.apt:
        name:
          - httpd
        cache_valid_time: 20

