---

- hosts: demo for auto completion for Ansible Module
  tasks:
    - name: hello world {{ ansible }} this is very cool :)
      ap

    - name: world
      action: an

    - name: block demo
      block:
        - name: block demo
          xxx
